name: Post tweet

on:
  schedule:
  - cron: "0,30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tweet
      env:
        GITHUB_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        TWITTER_CONSUMER_KEY: ${{ secrets.API_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.API_KEY_SECRET }}
      run: |
        python run.py
